version: 2.1
jobs:
  envvar_test:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: プロジェクト設定の環境変数を出力する
          command: echo $PROJECT_VARIABLE

workflows:
  version: 2
  main:
    jobs:
      - envvar_test
