orbs:
  pr-comment: benjlevesque/pr-comment@0.1.4
version: 2.1
jobs:
  pull_request_comment_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - pr-comment/pr-comment:
          comment: GitHubプルリクエストにコメント
          maxComments: 10
workflows:
 version: 2
 main:
   jobs:
     - pull_request_comment_test
