version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: BASE64を利用して複数行の環境変数を扱う
          environment:
            MULTILINE_ENV_VAR: MeihjOebrgoy6KGM55uuCg==
          command: |
            echo $MULTILINE_ENV_VAR | base64 --decode
