version: 2.1
jobs:
  deploy_key_test:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:fc:38:b1:76:a7:51:38:da:e9:7f:c8:07:07:8a:0b"
      - checkout

workflows:
 version: 2
 main:
   jobs:
     - deploy_key_test
