orbs:
  slack: circleci/slack@3.4.0
version: 2.1
jobs:
  slack_test:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Slack test uisng curl
          command: |
            curl -X POST -H 'Content-type:application/json' \
            --data "{'text':'Hi!'}" ${SLACK_WEBHOOK}
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - slack_test:
         context: SLACK_INTEGRATION
