version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6
    steps:
      - checkout
      - run:
          command: ls -al ~/
      - run:
          command: ls -al /
      - run:
          command: ls -al /root
