version: 2.1
jobs:
  deploy_key_test:
    docker:
      - image: circleci/node:10
    steps:
      # - run:
      #     command: ls -al ~/
      # - checkout
      # - run:
      #     command: ls -al ~/.ssh
      # - run:
      #     command: cat ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "e4:76:09:45:8f:fc:3d:7f:c0:6e:7b:e6:c5:6d:37:3c"
      - run:
          command: ls -al ~/.ssh
      # - run:
      #     command: cat ~/.ssh/known_hosts
      - run:
          command: cat ~/.ssh/config
      - run:
          command: git clone git@github.com:tomoya/new-circleci-project-private.git
      # - add_ssh_keys:
      #     fingerprints:
      #       - "72:fc:38:b1:76:a7:51:38:da:e9:7f:c8:07:07:8a:0b"
      # - run:
      #     command: ls -al ~/.ssh
      # - run:
      #     command: cat ~/.ssh/config
      # - run:
      #     command: git push origin master

workflows:
 version: 2
 main:
   jobs:
     - deploy_key_test
