version: 2.1
jobs:
  slack_test:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Slack test uisng curl
          command: |
            curl -X POST -H 'Content-type:application/json' \
            --data "{'text':'Hi!'}" ${SLACK_WEBHOOK}

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - slack_test:
         context: SLACK_INTEGRATION
